# Generated by Django 6.0.3 on 2026-03-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='client',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
